---
# defaults file for networking 101 system
aws_account_num: "{{ vault_aws_account_num }}"
public_key: '{{ envname }}'
region: eu-west-1
cidr_block: "10.1.0.0/16"
b_class_cidr: "{{ cidr_block.split('.')[0] }}.{{ cidr_block.split('.')[1] }}"
###############################################
env_instance_type: t2.micro
default_num_of_instances: 1
###############################################
vpn_instance_type: "{{ env_instance_type }}"
vpn_ami: "ami-xxxxx"
###############################################
webserver_instance_type: "{{ env_instance_type }}"
webserver_ami: "ami-xxxxx"
webserver_num_of_instances: "{{ default_num_of_instances }}"
###############################################
subnets:
 public:
   subnet_name: "public-{{ envname }}"
   ipv4_cidr: "{{ b_class_cidr }}.1.0/24"
   availability_zone: "{{ region }}a"
 # public-secondary:
 #   subnet_name: "public_secondary-{{ envname }}"
 #   ipv4_cidr: "{{ b_class_cidr }}.101.0/24"
 #   availability_zone: "{{ region }}b"
 private:
   subnet_name: "private-{{ envname }}"
   ipv4_cidr: "{{ b_class_cidr }}.2.0/24"
   availability_zone: "{{ region }}a"
 # private-secondary:
 #   subnet_name: "private-{{ envname }}"
 #   ipv4_cidr: "{{ b_class_cidr }}.3.0/24"
 #   availability_zone: "{{ region }}c"
 # rds:
 #   subnet_name: "rds-{{ envname }}"
 #   ipv4_cidr: "{{ b_class_cidr }}.5.0/24"
 #   availability_zone: "{{ region }}b"
services:
  - name: webservice
    type: "{{ webserver_instance_type }}"
    extelb: True
    num_of_instances: "{{ webserver_num_of_instances }}"
# ansible varialbes for infra security groups
# sg_infra_default_vpn_ssh: sg-0a35fa72
# sg_infra_vpn: sg-2462ad5c
###################################################
#security_groups:
   - description: Allow SSH from VPN
     name: "{{ envname }}_allow_ssh_from_vpn"
     rules:
         - proto: tcp
           from_port: 22
           to_port: 22
           group_id: "{{ sg_infra_vpn }}"
   - description: Allow 80 from VPN
     name: "{{ envname }}_allow_from_vpn"
     rules:
         - proto: tcp
           from_port: 80
           to_port: 80
           group_id: "{{ sg_infra_vpn }}"
#################################################################
aws_access_key: "{{ vault_aws_access_key }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
#################################################################