---
# tasks file for ops
- name: APT install
  with_items:
      - unzip
      - apache2
  apt:
      name: '{{ item }}'
      state: present
      update_cache: yes
      cache_valid_time: 3600
  notify: restart http
